language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t foal90/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true foal90/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-354294264644"
  bucket_path: "docker_react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY